version: '3.8'

services:
  squid-balancing:
    build: .
    container_name: squid_balancing
    networks:
      squidnet:
        ipv4_address: 192.168.100.10  
    ports:
      - "3128:3128"
    volumes:
      - ./logs/balanceador:/var/log/squid
      - ./balanceador/squid.conf:/etc/squid/squid.conf:ro
      - ./balanceador/squid.d:/etc/squid/squid.d:ro
      - ./ssl_certs:/etc/ssl/squid_certs:ro
      - /etc/squid/usuarios_bloqueados.txt:/etc/squid/usuarios_bloqueados.txt:ro
    restart: unless-stopped
    depends_on:
      - squid-backend1
      - squid-backend2
      - squid-backend3

  squid-backend1:
    build: .
    container_name: squid_backend1
    networks:
      squidnet:
        ipv4_address: 192.168.100.11 
    volumes:
      - ./logs/backend1:/var/log/squid
      - ./backend1/squid.conf:/etc/squid/squid.conf:ro
      - ./backend1/squid.d:/etc/squid/squid.d:ro
    restart: unless-stopped

  squid-backend2:
    build: .
    container_name: squid_backend2
    networks:
      squidnet:
        ipv4_address: 192.168.100.12  
    volumes:
      - ./logs/backend2:/var/log/squid
      - ./backend2/squid.conf:/etc/squid/squid.conf:ro
      - ./backend2/squid.d:/etc/squid/squid.d:ro
    restart: unless-stopped

  squid-backend3:
    build: .
    container_name: squid_backend3
    networks:
      squidnet:
        ipv4_address: 192.168.100.13  
    volumes:
      - ./logs/backend3:/var/log/squid
      - ./backend3/squid.conf:/etc/squid/squid.conf:ro
      - ./backend3/squid.d:/etc/squid/squid.d:ro
    restart: unless-stopped

networks:
  squidnet:
    driver: bridge  
    ipam:
      config:
        - subnet: 192.168.100.0/24  # NUEVA subred
          gateway: 192.168.100.1     # Gateway automático