version: '3.8'

services:
  squid:
    build:
      context: .
      # You can pass build args here to change the squid package version and distro
      # args:
      #   SQUID_VERSION: "7.1"
      #   DISTRO: "jammy"
    container_name: squid_proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid_logs:/var/log/squid        # añade :Z si usas SELinux
      - ./squid_cache:/var/spool/squid     # opcional: persistir caché
      - ./squid.conf:/etc/squid/squid.conf
    restart: unless-stopped

  php-app:
    build: ./sqstats
    container_name: php_app
    ports:
      - "80:80"
    restart: unless-stopped
