services:
  squid:
    build:
      context: .
      # You can pass build args here to change the squid package version and distro
      # args:
      #   SQUID_VERSION: "7.1"
      #   DISTRO: "jammy"
    container_name: squid_proxy
    depends_on:
      - squid-parent
    networks:
      proxy_net:
        ipv4_address: 172.30.0.2
    ports:
      - "3128:3128"
      #- "80:5000"
    volumes:
      - ./squid_logs:/var/log/squid
      - ./squid.conf:/etc/squid/squid.conf
      - ./ssl_certs:/etc/ssl/squid_certs
      - ./squid.d/reglas:/etc/squid/reglas
      #- /etc/squid/squid.conf:/etc/squid/squid.conf
      #- /etc/squid/squid.d:/etc/squid/squid.d  # Config modular
    restart: unless-stopped

  squid-parent:
    build:
      context: .
    # Reutiliza la misma imagen de Squid; solo cambia la configuración.
    container_name: squid_parent_proxy
    networks:
      proxy_net:
        ipv4_address: 172.30.0.3
    expose:
      - "3128"
    volumes:
      - ./squid_parent_logs:/var/log/squid
      - ./squid-parent.conf:/etc/squid/squid.conf
    restart: unless-stopped

  #php-app:
    #build: ./sqstats
    #container_name: php_app
    #ports:
      #- "80:80"
    #restart: unless-stopped

networks:
  proxy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
