[libdefaults]
    default_realm = INUTIL.CU
    dns_lookup_realm = false
    dns_lookup_kdc = true
    rdns = false
    ticket_lifetime = 24h
    forwardable = true

[domain_realm]
    .inutil.cu = INUTIL.CU
    inutil.cu = INUTIL.CU
