http_port 3128

cache_effective_user proxy
cache_effective_group proxy

# Esta imagen instala las páginas base en templates, sin carpetas por idioma.
error_directory /usr/share/squid/errors/templates

cache_mem 64 MB
cache_dir ufs /var/spool/squid 100 16 256
visible_hostname squid-parent

access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log
pid_filename /var/run/squid.pid

# Solo acepta solicitudes del proxy hijo en la red interna de Compose.
acl proxy_hijo src 172.30.0.2/32
http_access allow proxy_hijo
http_access deny all
