# ============================================================
# CONFIGURACIÓN DEL BACKEND 1
# ============================================================

http_port 3128

cache_effective_user proxy
cache_effective_group proxy

max_filedescriptors 65536

cache_mem 64 MB
cache_dir ufs /var/spool/squid 100 16 256
visible_hostname squid-backend1

access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log
pid_filename /var/run/squid.pid

# ============================================================
# BACKEND - solo acepta tráfico desde el balanceador
# ============================================================

acl balanceador src 192.168.0.10
acl mired src 192.168.0.0/15
acl localhost src 127.0.0.1/32 ::1

http_access allow localhost
http_access allow balanceador
http_access allow mired
http_access deny all

access_log /var/log/squid/access.log combined
